version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
      - image: dwmkerr/dynamodb:38
    environment:
      TEST_STRIPE_KEY: sk_test_qqeGkZVE30FLH76H2g2Fd4NL
    steps:
      - checkout
      - run: yarn
      - run: yarn run bootstrap
      - run: yarn run tslint
      - run: yarn run build
